# Generated by Django 4.2 on 2023-04-11 05:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_subcategory_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
