# Generated by Django 4.2 on 2023-04-11 05:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
