# Generated by Django 4.2 on 2023-05-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='sale_id',
            new_name='order_id',
        ),
    ]
